# Generated by Django 5.2 on 2025-05-04 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BTdetection', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('address', 'city', 'state', 'country', 'zip_code')},
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BTdetection.address'),
        ),
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
    ]
