# Generated by Django 5.2 on 2025-05-11 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BTdetection', '0003_passwordresettoken'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('city', 'state', 'country', 'zip_code')},
        ),
        migrations.RemoveField(
            model_name='address',
            name='address',
        ),
    ]
