# Generated by Django 5.2 on 2025-05-26 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BTdetection", "0005_scan_prediction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scan",
            name="upload_date",
        ),
        migrations.AddField(
            model_name="scan",
            name="scan_file",
            field=models.FileField(default="default.nii", upload_to="scans/"),
        ),
    ]
